### ISSUE TITLE
Grid system for site

### ISSUE THREAD

**Issue by cassidyclawson** [cassidyclawson/cassidy-clawson#2]
Please continue create responsive fluid layout. I need three breakpoints. The large and medium size shall continue to use highlight effect. The small should use no highlight effect.

Please see diagrams below. I have included some child divs to show my intentions for content structure.

Large (Desktop):
![image](https://cloud.githubusercontent.com/assets/6835484/9103649/6068b964-3bb5-11e5-81f3-d572294e8627.png)

Medium (Sm. desktop / tablet)

![image](https://cloud.githubusercontent.com/assets/6835484/9103655/6f001b52-3bb5-11e5-8696-d2337ba37dc1.png)

Small 
![image](https://cloud.githubusercontent.com/assets/6835484/9103656/76a2939e-3bb5-11e5-94c9-4a6427fdda36.png)

**Comment by alokjain-lucky** [comment]
I am not clear about 1.1 and 1.2 
- Do you want me to highlight 1.1 and 1.2 and then move to box 2 ? Or just highlight box 1 and them box 2
-  For Medium (Sm. desktop / tablet), Do you want any box having 2 children to be horizontal? or just first one?

**Comment by cassidyclawson** [comment]
Only the first box (1) has nested child divs (1.1 and 1.2). They do not need any special highlighting treatment. They should be highlighted along with the rest of the content in the first box. 

Only first box has horizontal content in medium.

**Comment by alokjain-lucky** [comment]
On laptop screen, or on tablet etc. there is not enough space to fit the design in visible area. 

Please see attached screenshot:
If we make First column horizontal, another 2 columns will be pushed down. But there is not enough space to show all 3 blocks in available screen space.

![image](https://cloud.githubusercontent.com/assets/5526402/9954319/b463c9c4-5e05-11e5-88bb-b8e417f6b89a.png)

**Comment by alokjain-lucky** [comment]
Also for code block, i have used spans for code colouring, do you think we need to use any JS library for this ?
