### ISSUE TITLE
Create archive of DataPath work 

### ISSUE THREAD

**Issue by cassidyclawson** [cassidyclawson/cassidy-clawson#4]
Please produce a .zip file that contains ALL of the WordPress improvements we made for DataPath that they never finished. Please include database dump and anything else the client may need. I want to send this to them in case they ever want it.

**Comment by alokjain-lucky** [comment]
Link to Zip file, with all files and database. 
https://www.dropbox.com/s/zo6yyerlrp2jp44/mydatapath.zip?dl=0

**Comment by cassidyclawson** [comment]
Delivered to datapath
