### ISSUE TITLE
Migrate cassidyclawson.com to github hosting

### ISSUE THREAD

**Issue by cassidyclawson** [cassidyclawson/cassidy-clawson#8]
Please setup this repo so that github hosts it with static site feature.

**Comment by alokjain-lucky** [comment]
Please review here: https://cassidyclawson.github.io/cassidy-clawson/

I will change domain pointing after your confirmation.

**Comment by cassidyclawson** [comment]
👍

**Comment by alokjain-lucky** [comment]
Please add domain on settings of repository.
https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

I do not have access to settings.

**Comment by cassidyclawson** [comment]
Token that sends to my dad, ben@clawsondevicegroup.com

Form API token: ba050685a30fbe6085fcd73b007b7477
This is like your public key and its embedded in your form's 'action' attribute.
Access API token: a1bc02d15ef88fec4aa6b2a1d98ec162
This is like your private key. You should not share this with anyone. This allows you to access all the data associated with your form.
